name: GamemodeCommand
version: 1.0.1
main: com.ShingWong08.Main
commands:
  gamemode:
    description: Change Your Gamemode
    usage: /<command>
    aliases:
      - gm
  gmc:
    description: Change Your Gamemode To Creative Mode
    usage: /<command>
    aliases:
      - gm1
  gms:
    description: Change Your Gamemode To Survival Mode
    usage: /<command>
    aliases:
      - gm0
  gma:
    description: Change Your Gamemode To Adventure Mode
    usage: /<command>
    aliases:
      - gm2
  gmsp:
    description: Change Your Gamemode To Spectator Mode
    usage: /<command>
    aliases:
      - gm3
  gamemodepluginversion:
    description: Check The Gamemode Plugin Version
    usage: /<command>
    aliases:
      - gamemodeversion
      - gmversion
      - gamemodever
      - gmver